# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20170705_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='不愿透露身份的人', max_length=50),
        ),
    ]
